#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
#cursor fix
xsetroot -cursor_name left_ptr &
# para dar transparencia poner en picom.conf backed = "xrender" y al parecer solo una vez ejecutar esto:
picom --experimental-backends &
pgrep -x picom | picom &
# restaurar fondo con feh
~/.fehbg &
# recordatorio
dunstify -i $HOME/.config/dunst/icon/arch-03.jpg "OPRIME" "super + shift + m" 

### jala del script para dual monitor, si es solo un monitor:
#bspc monitor -d  一 二 三 四 五 六 七 八 九 零

bspc config border_width			2
#Esto crea un relleno negativo igual al espacio de la ventana para que los espacios se muestren solo entre las ventanas y no en los bordes del escritorio.
# valor inmutable al parecer
bspc config split_ratio				0.52
# al poner el puntero encima de una ventana esta se enfoca
bspc config focus_follows_pointer		false
# espaciado de las ventanas
bspc config window_gap				15
bspc config focused_border_color "#f7768e"
bspc config presel_feedback_color "#C9CBFF"

bspc config borderless_monocle			true
bspc config gapless_monocle			false
bspc config single_monocle			true


### anchoxalto
bspc rule -a firefox state=floating center=on rectangle=1400x700+0+0
bspc rule -a Spotify state=floating center=on rectangle=1200x1000+0+0
bspc rule -a kitty state=tiled
