#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
php -S localhost:8080 -t $HOME/Simple-Start-page > /dev/null
xsetroot -cursor_name left_ptr &
# para dar transparencia poner en picom.conf backed = "xrender"
# al parecer solo una vez ejecutar esto
#picom --experimental-backends &
pgrep -x picom | picom &
bspc monitor -d  一 二 三 四 五 六 七 八 九 零

#______________________BORDES Y COLORES/CONF BSPWM_______________________

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#___________________ FullCOLOR Theme _______________________
bspc config urgent_border_color "#dd2727"
bspc config focused_border_color "#03B4CB"
bspc config presel_feedback_color "#C9CBFF"
